---
title: A_Coroutines_Intro.RxSubscriber.onError - 
layout: api
---

<div class='api-docs-breadcrumbs'><a href="../../index.html">pl.mareklangiewicz.myblog.coroutines</a> / <a href="../index.html">A_Coroutines_Intro</a> / <a href="index.html">RxSubscriber</a> / <a href=".">onError</a></div>

# onError

<div class="signature"><code><span class="keyword">fun </span><span class="identifier">onError</span><span class="symbol">(</span><span class="parameterName" id="pl.mareklangiewicz.myblog.coroutines.A_Coroutines_Intro.RxSubscriber$onError(kotlin.Throwable)/t">t</span><span class="symbol">:</span>&nbsp;<span class="identifier">Throwable</span><span class="symbol">)</span><span class="symbol">: </span><span class="identifier">Unit</span></code></div>

Resumes the coroutine with given exception

