[pl.mareklangiewicz.myblog.coroutines](../../index.md) / [A_Coroutines_Intro](../index.md) / [RxSubscriber](index.md) / [onError](.)

# onError

`fun onError(t: Throwable): Unit`

Resumes the coroutine with given exception

